import { createHash, randomUUID } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { BadRequestException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import { and, eq } from "drizzle-orm";
import type { Db } from "../db/client";
import { DB_TOKEN } from "../db/token";
import { withActor, SERVICE } from "../db/actor";
import { files } from "../db/schema";
import { config } from "../config";

/**
 * Uploaded files — the storage half of classwork.
 *
 * Design rules, in order of importance:
 *
 *  1. **Never inside the web root.** Files land in `FILES_DIR` (a private
 *     volume in compose), not under public/. There is no URL that maps to a
 *     file; the only way in is `GET /api/v1/files/:id`, which re-checks the
 *     caller's scope on every request. A directory-traversal attempt has
 *     nowhere to traverse to.
 *  2. **The name on disk is random.** `stored_name` is a UUID; the school's
 *     original name lives in the database only and is sent back as the
 *     `Content-Disposition` filename. Two teachers uploading "homework.pdf"
 *     cannot collide or overwrite each other.
 *  3. **Type is decided by an allowlist, and the extension given to the file is
 *     derived from the MIME type, never from the uploaded name** — the same
 *     rule the site's news uploader already follows, for the same reason: an
 *     uploaded `.html`/`.svg` must never be servable as an executable document.
 */
@Injectable()
export class FilesService {
  constructor(@Inject(DB_TOKEN) private db: Db) {}

  dir(): string {
    return path.resolve(config.files.dir);
  }

  private ensureDir(): string {
    const dir = this.dir();
    fs.mkdirSync(dir, { recursive: true });
    return dir;
  }

  /** Absolute path for a stored name, refusing anything that is not a plain name. */
  pathFor(storedName: string): string {
    if (!/^[a-f0-9-]{36}\.[a-z0-9]{1,8}$/i.test(storedName)) {
      // Belt and braces: stored_name is generated by us, so anything else is
      // either corruption or an attack. Never join it onto the filesystem.
      throw new NotFoundException({ code: "not_found" });
    }
    return path.join(this.dir(), storedName);
  }

  private extFor(mime: string): string {
    const map: Record<string, string> = {
      "application/pdf": "pdf",
      "image/jpeg": "jpg", "image/png": "png", "image/webp": "webp",
      "image/gif": "gif", "image/heic": "heic",
      "text/plain": "txt", "text/csv": "csv",
      "application/msword": "doc",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "docx",
      "application/vnd.ms-excel": "xls",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx",
      "application/vnd.ms-powerpoint": "ppt",
      "application/vnd.openxmlformats-officedocument.presentationml.presentation": "pptx",
      "application/zip": "zip",
    };
    return map[mime] ?? "bin";
  }

  /**
   * Validate a multer-uploaded temp file, copy it into the private store and
   * record it. Returns the row.
   *
   * The bytes are hashed as they are copied so the school can prove later that
   * a submitted file has not been altered — useful when a mark is disputed.
   */
  async store(input: {
    ownerUserId: string;
    tempPath: string;
    filename: string;
    mimeType: string;
  }) {
    if (!config.files.allowedMime.includes(input.mimeType)) {
      throw new BadRequestException({
        code: "unsupported_file_type",
        detail: `"${input.filename}" is a ${input.mimeType || "unknown"} file. ` +
          `Accepted: PDF, Word, Excel, PowerPoint, images, text/CSV and ZIP.`,
      });
    }
    const dir = this.ensureDir();
    const storedName = `${randomUUID()}.${this.extFor(input.mimeType)}`;
    const dest = path.join(dir, storedName);

    const hash = createHash("sha256");
    let bytes = 0;
    await new Promise<void>((resolve, reject) => {
      const read = fs.createReadStream(input.tempPath);
      const write = fs.createWriteStream(dest, { mode: 0o600 });
      read.on("data", (chunk) => { hash.update(chunk); bytes += chunk.length; });
      read.on("error", reject);
      write.on("error", reject);
      write.on("close", resolve);
      read.pipe(write);
    });

    // The temp copy is multer's; ours is the one that lives.
    fs.rmSync(input.tempPath, { force: true });

    if (bytes === 0) {
      fs.rmSync(dest, { force: true });
      throw new BadRequestException({ code: "empty_file", detail: "That file is empty." });
    }

    // Raw service actor: storage is infrastructure, not an actor action. The
    // scope checks happen where the file is attached, and on every download.
    return withActor(this.db, SERVICE, async (tx) => {
      const [row] = await tx.insert(files).values({
        ownerUserId: input.ownerUserId,
        filename: input.filename.slice(0, 200),
        storedName,
        mimeType: input.mimeType,
        bytes,
        sha256: hash.digest("hex"),
      }).returning();
      return row;
    });
  }

  /**
   * A file row the caller is allowed to read.
   *
   * RLS does the real work (files_sel + can_read_file). This runs as the caller
   * so a file attached to a section the caller has nothing to do with comes
   * back as null — i.e. 404, not 403: a stranger should not learn that an id
   * exists.
   */
  async readable(actor: { userId: string; role: string }, id: string) {
    return withActor(this.db, actor, async (tx) => {
      const [row] = await tx.select().from(files)
        .where(and(eq(files.id, id))).limit(1);
      return row ?? null;
    });
  }

  /** Drop a file's bytes and row. Used by material/assignment delete paths. */
  async remove(id: string) {
    const [row] = await withActor(this.db, SERVICE, async (tx) =>
      tx.select().from(files).where(eq(files.id, id)).limit(1));
    if (!row) return false;
    fs.rmSync(path.join(this.dir(), row.storedName), { force: true });
    await withActor(this.db, SERVICE, async (tx) => {
      await tx.delete(files).where(eq(files.id, id));
    });
    return true;
  }
}
