#!/usr/bin/env node
/**
 * Vendor public/assets/css/tokens.css into the portal.
 *
 * WHY A COPY AND NOT AN @IMPORT (PORTAL-INTEGRATION-PLAN.md §3.2a)
 * portal/Dockerfile copies only package.json, package-lock.json,
 * tsconfig.base.json, packages/, apps/, db/ and scripts/ into the image —
 * nothing outside the portal root. An `@import
 * "../../../public/assets/css/tokens.css"` therefore resolves on a developer's
 * disk and fails `next build` inside Docker, where that path does not exist.
 *
 * So tokens.css is the single source of truth here and is COPIED into
 * portal/apps/web/app/tokens.css. This script keeps the two in step:
 *
 *   npm run tokens:sync    write the copy
 *   npm run tokens:check   exit 1 if the copy has drifted (for CI)
 */
'use strict';

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'public', 'assets', 'css', 'tokens.css');
const DEST = path.join(__dirname, '..', 'portal', 'apps', 'web', 'app', 'tokens.css');

const BANNER = `/* ============================================================
   AUTO-VENDORED — DO NOT EDIT THIS FILE.
   Source of truth: public/assets/css/tokens.css
   Regenerate:  npm run tokens:sync     Verify:  npm run tokens:check
   ============================================================ */

`;

function main() {
  const check = process.argv.includes('--check');

  if (!fs.existsSync(SRC)) {
    console.error(`[tokens] source not found: ${path.relative(process.cwd(), SRC)}`);
    process.exit(1);
  }

  const source = fs.readFileSync(SRC, 'utf8');
  const expected = BANNER + source;

  if (check) {
    const actual = fs.existsSync(DEST) ? fs.readFileSync(DEST, 'utf8') : null;
    if (actual === expected) {
      console.log('[tokens] in sync ✓');
      return;
    }
    console.error('[tokens] DRIFT DETECTED — the vendored copy is out of date.');
    console.error(`[tokens]   source: ${path.relative(process.cwd(), SRC)}`);
    console.error(`[tokens]   copy:   ${path.relative(process.cwd(), DEST)}`);
    console.error('[tokens] Run `npm run tokens:sync` and commit the result.');
    process.exit(1);
  }

  fs.mkdirSync(path.dirname(DEST), { recursive: true });
  fs.writeFileSync(DEST, expected);
  console.log(`[tokens] vendored ${source.length} bytes → ${path.relative(process.cwd(), DEST)}`);
}

main();
